name: fanatactivity
version: 1

worker: tornado

libraries:
- name: tornado
  version: "3.1.1"

- name: jinja2
  version: "2.6"

- name: MySQLdb
  version: "1.2.3"

- name: PyCrypto
  version: "2.6"

- name: PyYAML
  version: "3.10"

handlers:
- url: /static/
  static_path: static

- url: /favicon.ico
  static_path: favicon.ico